name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
          tools: composer

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Build plugin zip
        run: |
          PLUGIN_SLUG="opendoliconnect"
          VERSION="${GITHUB_REF_NAME#v}"
          ZIPNAME="${PLUGIN_SLUG}-${VERSION}.zip"
          zip -r "$ZIPNAME" "${PLUGIN_SLUG}" -x "**/vendor/**" "**/.git/**" "**/.github/**"
          echo "ZIP built: $ZIPNAME"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: "*.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
